// WARNING
// This file was autogenerated, and _will_ be overwritten by Halyard.
// Any edits you make here _will_ be lost.

'use strict';

var feedbackUrl = '';
var gateHost = 'http://localhost:8084';
var bakeryDetailUrl = (gateHost + '/bakery/logs/{{context.region}}/{{context.status.resourceId}}');
var authEndpoint = (gateHost + '/auth/user');
var authEnabled = false;
var chaosEnabled = false;
var fiatEnabled = false;
var jobsEnabled = false;
var canaryEnabled = true;
var pipelineTemplatesEnabled = false;
var timezone = 'America/Los_Angeles';
var version = '1.3.1';
var changelogGistId = '021ff67e0ef7a4e1b271e0ea4344b3b4';
var changelogGistName = 'changelog.md';
var gce = {
  defaults: {
    account: '',
    region: 'us-central1',
    zone: 'us-central1-f'
  },
  associatePublicIpAddress: true,
};
var kubernetes = {
  defaults: {
    account: 'my-os-account',
    namespace: 'default',
    proxy: 'localhost:8001',
    internalDNSNameTemplate: '{{name}}.{{namespace}}.svc.cluster.local',
    instanceLinkTemplate: '{{host}}/api/v1/proxy/namespaces/{{namespace}}/pods/{{name}}',
  }
};
var appengine = {
  defaults: {
    account: '',
    editLoadBalancerStageEnabled: false
  }
};
var openstack = {
  defaults: {
    account: '',
    region: '{%openstack.default.region%}'
  }
};
var azure = {
  defaults: {
    account: '',
    region: 'westus'
  }
};
var oraclebmcs = {
  defaults: {
    account: '{%oraclebmcs.default.account%}',
    region: '{%oraclebmcs.default.region%}'
  }
};
var dcos = {
  defaults: {
    account: ''
  }
};
var entityTagsEnabled = false;
var netflixMode = false;

window.spinnakerSettings = {
  version: version,
  checkForUpdates: false,
  defaultProviders: ['aws', 'gce', 'azure', 'cf', 'kubernetes', 'titus', 'openstack', 'oraclebmcs', 'dcos'],
  feedbackUrl: feedbackUrl,
  gateUrl: gateHost,
  bakeryDetailUrl: bakeryDetailUrl,
  authEndpoint: authEndpoint,
  pollSchedule: 30000,
  defaultTimeZone: timezone, // see http://momentjs.com/timezone/docs/#/data-utilities/
  defaultCategory: 'serverGroup',
  defaultInstancePort: 80,
  providers: {
    azure: azure,
    aws: {
      defaults: {
        account: 'test',
        region: 'us-east-1',
        iamRole: 'BaseIAMRole',
      },
      defaultSecurityGroups: [],
      loadBalancers: {
        // if true, VPC load balancers will be created as internal load balancers if the selected subnet has a purpose
        // tag that starts with "internal"
        inferInternalFlagFromSubnet: false,
      },
      useAmiBlockDeviceMappings: false,
    },
    gce: gce,
    titus: {
      defaults: {
        account: 'titustestvpc',
        region: 'us-east-1',
        iamProfile: '{{application}}InstanceProfile',
      },
    },
    openstack: openstack,
    kubernetes: kubernetes,
    appengine: appengine,
    oraclebmcs: oraclebmcs,
    dcos: dcos
  },
  changelog: {
    gistId: changelogGistId,
    fileName: changelogGistName,
  },
  notifications: {
    email: {
      enabled: true,
    },
    hipchat: {
      enabled: true,
      botName: 'Skynet T-800'
    },
    sms: {
      enabled: true,
    },
    slack: {
      enabled: true,
      botName: 'spinnakerbot'
    }
  },
  authEnabled: authEnabled,
  authTtl: 600000,
  gitSources: ['stash', 'github', 'bitbucket'],
  triggerTypes: ['git', 'pipeline', 'docker', 'cron', 'jenkins', 'travis'],
  feature: {
    canary: canaryEnabled,
    entityTags: entityTagsEnabled,
    fiatEnabled: fiatEnabled,
    netflixMode: netflixMode,
    chaosMonkey: chaosEnabled,
    jobs: jobsEnabled,
    pipelineTemplates: pipelineTemplatesEnabled,
    pipelines: true,
    notifications: false,
    fastProperty: true,
    vpcMigrator: true,
    clusterDiff: false,
    roscoMode: true,
    infrastructureStages: false,
    snapshots: false,
    travis: false,
  },
};
